# Generated by Django 4.2.1 on 2023-05-17 04:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_activity_activity_name_alter_activity_datetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='company',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
